name: Lint Spring Boot Project 
on: 
  push: 
    branches: [ main ] 
 
jobs: 
  lint: 
    runs-on: ubuntu-latest 
 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 
 
      - name: Set up JDK 17 
        uses: actions/setup-java@v3 
        with: 
          java-version: 17 
          distribution: temurin 
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true
          job-status: success
 
     # - name: Run Checkstyle 
      #  run: | 
       #   mvn clean checkstyle:checkstyle -Dcheckstyle.config.file=checkstyle.xml

      - name: Set up Maven
        uses: s4u/setup-maven@v1.3.1
        with:
         maven-version: '3.8.1'
 

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17  # Same version as above (JDK 17)
          distribution: temurin

      - name: Run PMD Analysis
        run: mvn pmd:pmd  # Run PMD via Maven
        #run: mvn clean verify
      
        
    
