name: Lint Spring Boot Project 
on: 
  push: 
    branches: [ main ] 
 
jobs: 
  lint: 
    runs-on: ubuntu-latest 
 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 
 
      - name: Set up JDK 17 
        uses: actions/setup-java@v3 
        with: 
          java-version: 17 
          distribution: temurin 
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true
          job-status: success
 
     # - name: Run Checkstyle 
      #  run: | 
       #   mvn clean checkstyle:checkstyle -Dcheckstyle.config.file=checkstyle.xml

     # - name: Set up Maven
      ##with:
       #  maven-version: '3.8.1'
 

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17  # Same version as above (JDK 17)
          distribution: temurin

      - name: Run PMD Analysis
        # - name: Run PMD Analysis
        run: |
          ./pmd/bin/run.sh pmd -d src/main/java -f text -R rulesets/java/basic.xml,rulesets/java/design.xml,rulesets/java/imports.xml,rulesets/java/naming.xml,rulesets/java/unusedcode.xml
          # If you want to fail the workflow on violations, you'll need to parse the output
          # and set the exit code accordingly. This is more complex than the Maven plugin.

      - name: (Optional) Fail Workflow on Violations (Example - Basic Parsing)
        id: check_pmd
        run: |
          violations=$(./pmd/bin/run.sh pmd -d src/main/java -f text -R rulesets/java/basic.xml,rulesets/java/design.xml,rulesets/java/imports.xml,rulesets/java/naming.xml,rulesets/java/unusedcode.xml | grep "ruleset")
          if [[ -n "$violations" ]]; then
            echo "::error::PMD violations found:"
            echo "$violations"
            exit 1
          fi
          
        
    
