name: pmd
on:
  push:
    branches: [ main ]
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Download PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases/6.55.0/pmd-bin-6.55.0.zip
          unzip pmd-bin-6.55.0.zip
          mv pmd-bin-6.55.0 pmd

      - name: Create Custom PMD Ruleset
        run: |
           cat <<EOF > custom-pmd-ruleset.xml
            <?xml version="1.0"?>
            <ruleset name="Custom PMD Ruleset"
                xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/xsd/ruleset_2_0_0.xsd">
              <description>Custom PMD ruleset using PMD 7 categories and excluding variable name length checks.</description>

              <!-- Best practices -->
              <rule ref="category/java/bestpractices.xml"/>

              <!-- Code style -->
              <rule ref="category/java/codestyle.xml">
                <exclude name="ShortVariable"/>
                <exclude name="LongVariable"/>
              </rule>

              <!-- Error handling and logic -->
              <rule ref="category/java/errorprone.xml"/>

              <!-- Unused code -->
              <rule ref="category/java/unnecessary.xml"/>
              <rule ref="category/java/unusedcode.xml"/>
            </ruleset>
            EOF


      - name: Run PMD Analysis
        id: pmd-analysis
        run: ./pmd/bin/run.sh pmd -d src/main/java -f text -R custom-pmd-ruleset.xml

      - name: Fail if PMD violations are found
        if: steps.pmd-analysis.outcome == 'failure'
        run: exit 1
