name: Lint Spring Boot Project 
on: 
  push: 
    branches: [ main ] 
 
jobs: 
  lint: 
    runs-on: ubuntu-latest 
 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 
 
      - name: Set up JDK 17 
        uses: actions/setup-java@v3 
        with: 
          java-version: 17 
          distribution: temurin 
 
     # - name: Run Checkstyle 
      #  run: | 
       #   mvn clean checkstyle:checkstyle -Dcheckstyle.config.file=checkstyle.xml

      #- name: Set up Maven
       # uses: actions/setup-java@v2
        #with:
         # java-version: '11'
          #maven-version: '3.8.1'


      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17  # Same version as above (JDK 17)
          distribution: temurin

      - name: Run PMD Analysis
        run: mvn pmd:pmd  # Run PMD via Maven

      - name: Upload PMD report
        uses: actions/upload-artifact@v2  # Make sure v2 is used
        with:
          name: pmd-report
          path: target/pmd/pmd.xml  # S
    
