name: pmd
on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true
          job-status: success

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Download PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases/6.55.0/pmd-bin-6.55.0.zip
          unzip pmd-bin-6.55.0.zip
          mv pmd-bin-6.55.0 pmd

      - name: Create Custom PMD Ruleset
        run: |
          cat <<EOF > custom-pmd-ruleset.xml
          <?xml version="1.0"?>
          <ruleset name="Custom PMD Ruleset"
                    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/xsd/ruleset_2_0_0.xsd">
              <description>Custom PMD ruleset for the project.</description>

              <rule ref="rulesets/java/basic.xml"/>
              <rule ref="rulesets/java/design.xml">
                  <exclude name="UseUtilityClass"/>
              </rule>
              <rule ref="rulesets/java/imports.xml"/>
              <rule ref="rulesets/java/naming.xml">
                  <exclude name="LongVariable"/>
                  <properties>
                      <property name="minimum" value="25"/>
                  </properties>
                  <exclude name="ShortVariable"/>
                  <properties>
                      <property name="minimum" value="2"/>
                  </properties>
              </rule>
              <rule ref="rulesets/java/unusedcode.xml">
                  #<exclude name="UnusedLocalVariable"/>
              </rule>
          </ruleset>
          EOF

      - name: Run PMD Analysis
        run: ./pmd/bin/run.sh pmd -d src/main/java -f text -R custom-pmd-ruleset.xml

     

