name: Lint Spring Boot Project 
on: 
  push: 
    branches: [ main ] 
 
jobs: 
  lint: 
    runs-on: ubuntu-latest 
 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 
 
      - name: Set up JDK 17 
        uses: actions/setup-java@v3 
        with: 
          java-version: 17 
          distribution: temurin 
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true
          job-status: success
 
     # - name: Run Checkstyle 
      #  run: | 
       #   mvn clean checkstyle:checkstyle -Dcheckstyle.config.file=checkstyle.xml

     # - name: Set up Maven
      ##with:
       #  maven-version: '3.8.1'
 

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17  # Same version as above (JDK 17)
          distribution: temurin

      - name: Download PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases/6.55.0/pmd-bin-6.55.0.zip
          unzip pmd-bin-6.55.0.zip
          mv pmd-bin-6.55.0 pmd

      - name: Run PMD Analysis
        run: ./pmd/bin/run.sh pmd -d src/main/java -f text -R rulesets/java/basic.xml,rulesets/java/design.xml,rulesets/java/imports.xml,rulesets/java/naming.xml,rulesets/java/unusedcode.xml
          
        
    
