name: On Pull Request or Push to Main

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [pmd_debug ]

jobs:
  lint:
    name: Lint Debug Variant
    uses: ./.github/workflows/lint.yml

  test:
    name: Test Debug Variant
    uses: ./.github/workflows/lint_pmd.yml
